#!/bin/bash

name=$1
conf_template=$2
conffile=$3
url=$4
app_root=$5


function configure_apache {

  cp -p $conf_template $conffile
  sed_str=$(echo $app_root | sed -e 's/\(\/\|\\\|&\)/\\&/g')
  sed -i "s/PROJECT_ROOT/$sed_str/g" $conffile
  sed -i "s/URL/$url/g" $conffile

  echo ""
  echo "Apache VirtualHost Konfiguration unter: $conffile"
  echo "App Root unter: $app_root"
  echo "URL: http://$url"


  echo "Apache reload"
  sudo service apache2 reload 2>&1 > /dev/null 
}

configure_apache
