#!/bin/bash

name=$1
conf_template=$2
conffile=$3
url=$4
if [ -z $name -o -z $conf_template -o -z $conffile -o -z $url] ; then
 echo "usage: $0 appname conf_template conffile url app_root"
 exit 1;
fi


function configure_apache {

  cp -p $conf_template $conffile
  sed_str=$(echo $app_root | sed -e 's/\(\/\|\\\|&\)/\\&/g')
  sed -i "s/PROJECT_ROOT/$sed_str/g" $conffile
  sed -i "s/URL/$url/g" $conffile

  echo ""
  echo "Apache VirtualHost Konfiguration unter: $conffile"
  echo "App Root unter: $app_root"
  echo "URL: http://$url"


  echo "Apache reload"
  sudo service apache2 reload 2>&1 > /dev/null 
}

configure_apache
